### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by iNomaD** [CityOfZion/neon-js#157]
How this library is used? Do I need babel or something? I am trying run simple example with `node x.js`
```
import Neon, {wallet} from '@cityofzion/neon-js'
const a = Neon.create.Account('ALfnhLg7rUyL6Jr98bzzoxz5J7m64fbR4s')
console.log(a.address) // ALfnhLg7rUyL6Jr98bzzoxz5J7m64fbR4s
const b = new wallet.Account('9ab7e154840daca3a2efadaf0df93cd3a5b51768c632f5433f86909d9b994a69')
console.log(b.privateKey) // 9ab7e154840daca3a2efadaf0df93cd3a5b51768c632f5433f86909d9b994a69
```
And it doesn't work
```
(function (exports, require, module, __filename, __dirname) { import Neon, {wallet} from '@cityofzion/neon-js'
                                                              ^^^^^^
SyntaxError: Unexpected token import
```

**Comment by snowypowers** [comment]
yes, you need babel if you want to run `import`

**Comment by iNomaD** [comment]
With which commands can I run this file after installing babel? I am new to NodeJS

**Comment by snowypowers** [comment]
you cant run `import` currently using cli. Try using `require` instead.

**Comment by iNomaD** [comment]
@snowypowers do you mean like this?
```
let neon_js = require('@cityofzion/neon-js')
let Neon = neon_js.default
let wallet = neon_js.wallet
const a = Neon.create.Account('ALfnhLg7rUyL6Jr98bzzoxz5J7m64fbR4s')
console.log(a.address) // ALfnhLg7rUyL6Jr98bzzoxz5J7m64fbR4s
const b = new wallet.Account('9ab7e154840daca3a2efadaf0df93cd3a5b51768c632f5433f86909d9b994a69')
console.log(b.privateKey) // 9ab7e154840daca3a2efadaf0df93cd3a5b51768c632f5433f86909d9b994a69
```
What's wrong?
```
TypeError: Neon.create.Account is not a function
    at Object.<anonymous> (C:\Projects\IDEAProjects\identity-contract\test.js:5:23)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
```

**Comment by snowypowers** [comment]
http://cityofzion.io/neon-js/installation.html

Please go to discord for such questions. Issues are meant for development, not tutorials.
