### ISSUE TITLE
dependency: uglify dependency

### ISSUE THREAD

**Issue by benjyz** [CityOfZion/neon-js#283]
```
🚨  /Users/me/project/node_modules/@cityofzion/neon-js/src/wallet/    at may_modify (eval at <anonymous> (.../tools/node.js:21:1), <anonymous>:8931:31)
    at TreeTransformer.abort [as before] (eval at <anonymous> (.../uglify-es/tools/node.js:21:1), <anonymous>:8541:74)
```

**Comment by snowypowers** [comment]
I cannot reproduce this error. Please elaborate on your environment.

**Comment by benjyz** [comment]
Node version: 8.11
NPM version: 5.6.0
Yarn version: 0.23.2
related to #284
