### ISSUE TITLE
Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by bommels** [CityOfZion/neon-js#290]
I have the following issue when running my script on my private testnet. Node version is v10.8, neon-js version is 3.9.2. 

My code: 
```
const Neon = require('@cityofzion/neon-js');

const account = new Neon.wallet.Account('MY_PRIVATE_KEY');

const privateNet = new Neon.rpc.Network({
    name: 'PrivateNet',
    extra: {
        neoscan: 'http://localhost:4000/api/main_net'
    }
});

Neon.default.add.network(privateNet);

const intent = Neon.api.makeIntent({NEO: 1, GAS: 1}, account.address);

Neon.api.sendAsset({
    net: 'PrivateNet',
    account: account,
    intents: intent,
}).then(rpcResponse => {
    console.log(rpcResponse);
}).catch(error => {
    console.log(error);
});
```

The result:
```
TypeError: Cannot read property 'replace' of null
    at ../node_modules/@cityofzion/neon-js/lib/index.js:12:94764
    at new Promise (<anonymous>)
    at e.exports (../node_modules/@cityofzion/neon-js/lib/index.js:12:94059)
    at e.exports (../node_modules/@cityofzion/neon-js/lib/index.js:12:83584)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

My private net is running without (known) issues, and retrieving the balance via neon-js works fine. 
EDIT: The above code also works fine on TestNet. My private net is running on 10332 and I verified this via curl as described <a href="http://cityofzion.io/neon-js/docs/en/basic_privnet.html">here</a>.

**Comment by snowypowers** [comment]
I cant help you with this stacktrace and I did not use `replace` anywhere in the code.

I just published a new version that contains an unminified version for nodejs. That should give you a better stacktrace.

**Comment by snowypowers** [comment]
Closing due to inactivity.
