### ISSUE TITLE
Request timing out everytime whenever I push transaction

### ISSUE THREAD

**Issue by mohit-lala** [CityOfZion/neon-js#391]
Error: timeout of 30000ms exceeded
    at createError (/home/hp/Projects/argowallet/node_modules/@cityofzion/neon-js/dist/index.js:13322:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (/home/hp/Projects/argowallet/node_modules/@cityofzion/neon-js/dist/index.js:18064:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)

**Comment by snowypowers** [comment]
this is usually due to you choosing a bad endpoint to send to. Alternatively, you can manually override the timeout to a larger number.
