### ISSUE TITLE
Unable to perform a transfer using transfer.js example from next branch

### ISSUE THREAD

**Issue by pitersky** [CityOfZion/neon-js#773]
I use https://github.com/CityOfZion/neon-js/blob/next/examples/advanced/transfer.js to make a GAS transfer. Node replied error 500.

2. My inputs are

```
const inputs = {
  fromAccount: new wallet.Account(
    "KwRkhiNzxvpLVuW292eQV1kyf9Dw4tit8Y8s2NXDm3RbrB2sKdrj"
  ),
  toAccount: new wallet.Account(
    "NXx9xwpH5tmAjsqbTyfZqFnQd74ME2eat5"
  ),
  tokenScriptHash: CONST.NATIVE_CONTRACT_HASH.GasToken,
  amountToTransfer: 1,
  systemFee: 0,
  networkFee: 0,
  networkMagic: 1234567890, //CONST.MAGIC_NUMBER.TestNet,
  nodeUrl: "http://seed2t.neo.org:20332",
};
```

3. Running with node gives following result:
```
$ node advanced/transfer.js 


 --- Today's Task ---
Sending 1 token 
from NXx9xwpH5tmAjsqbTyfZqFnQd74ME2eat5
to NXx9xwpH5tmAjsqbTyfZqFnQd74ME2eat5
  ✓ Transaction created 
  ✓ Token found 
  ✓ Network Fee set: 0.01049390 
  ✓ SystemFee set: 0.05977750
  ✓ Token funds found 
  ✓ Sufficient GAS for fees found (7027140) 
{
  size: 244,
  version: 0,
  nonce: 1712482933,
  sender: 'NXx9xwpH5tmAjsqbTyfZqFnQd74ME2eat5',
  sysfee: '5977750',
  netfee: '1049390',
  validuntilblock: 377673,
  attributes: [],
  signers: [
    {
      account: '0x998f20d231f5c0dc39c73627cf4e7b54dc560b84',
      scopes: 'CalledByEntry'
    }
  ],
  script: 'CxEMFIQLVtxUe07PJzbHOdzA9THSII+ZDBSEC1bcVHtOzyc2xzncwPUx0iCPmRTAHwwIdHJhbnNmZXIMFM924ovQBixKR47jVWEBExnzz6TSQWJ9W1I=',
  witnesses: [
    {
      invocation: 'DEAXWFWWVfAHHNib5/0Fax/JCef6T9IxBlTXl5Wnj/i0FixCVg2YnOpd5kEBITxlwlcfmNlZS/mWMAd4noCptGa2',
      verification: 'DCECpFcLZpD8RUExliuG8+KAr6h8E/amQyvtOxNyewQi5IZBVuezJw=='
    }
  ]
}
RpcError: Invalid
    at RPCClient.execute (C:\Users\yuris\projects\atomic\repos\neon-js\examples\node_modules\@cityofzion\neon-core\dist\index.js:27030:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async RPCClient.sendRawTransaction (C:\Users\yuris\projects\atomic\repos\neon-js\examples\node_modules\@cityofzion\neon-core\dist\index.js:26864:30)
    at async performTransfer (file:///C:/Users/yuris/projects/atomic/repos/neon-js/examples/advanced/transfer.js:255:18) {
  code: -500
}
```
Node reply looks like this:
```
{
    "jsonrpc": "2.0",
    "id": 1234,
    "error": {
        "code": -500,
        "message": "Invalid",
        "data": "   at Neo.Plugins.RpcServer.GetRelayResult(VerifyResult reason, UInt256 hash)\n   at Neo.Plugins.RpcServer.SendRawTransaction(JArray _params)\n   at Neo.Plugins.RpcServer.ProcessRequest(HttpContext context, JObject request)"
    }
}
```
What's wrong with this transaction?

**Comment by snowypowers** [comment]
Can you update `inputs.networkMagic` to use CONST.MAGIC_NUMBER.TestNet? Specifically, that line should read:

```
networkMagic: CONST.MAGIC_NUMBER.TestNet,
```

since you are on testnet. The number `1234567890` is a placeholder number that I use for private net.

**Comment by pitersky** [comment]
Thanks! I missed that when I was crafting send example. However, I am still getting 500 when network magic is set up properly.

**Comment by pitersky** [comment]
Ok, this is indeed was incorect testnet magic. As I was sending to rc-3 testnet node I must be used 844378958 as stated in github release notes. They are changing every new relase so should be careful with that :)
