### ISSUE TITLE
Error on neon-ledger-next branch (breaking jest)

### ISSUE THREAD

**Issue by comountainclimber** [CityOfZion/neon-js#787]
```
  Cannot find module './main' from 'index.js'
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:169:17)
      at Object.<anonymous> (node_modules/@cityofzion/neon-ledger-next/dist/index.js:14:14)
``` 

When I look in the `dist` folder there is no `main.js` just the `index.js` file... Could this be related?

**Comment by ixje** [comment]
I believe this has been resolved for while now

**Comment by coinone-eokgi** [comment]
This issue is still not resolved.
