### ISSUE TITLE
Error when trying to send GAS (TextEncoder is not defined)

### ISSUE THREAD

**Issue by lock9** [CityOfZion/neon-js#790]
Hi.

I'm using the 5.0.0-next.15 release. I'm trying to do a transfer, but I'm getting this error instead:

```
    at ScriptBuilder.emitString (/home/lock9/Workspace/project/node_modules/@cityofzion/neon-js/dist/webpack:/@cityofzion/neon-core/lib/sc/ScriptBuilder.js:113:1)
    at ScriptBuilder.emitAppCall (/home/lock9/Workspace/project/node_modules/@cityofzion/neon-js/dist/webpack:/@cityofzion/neon-core/lib/sc/ScriptBuilder.js:48:1)
    at GASContract.transfer (/home/lock9/Workspace/project/node_modules/@cityofzion/neon-js/dist/webpack:/@cityofzion/neon-js/src/experimental/nep17/base.ts:134:1)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I'm using Ubuntu 20.04.3 LTS

**Comment by ixje** [comment]
Have a look at this https://github.com/CityOfZion/neon-js/issues/701

**Comment by ixje** [comment]
@lock9 I know this is old but can we consider this issue resolved or should it stay open?

**Comment by ixje** [comment]
Closing assuming it is solved. Let me know if we should re-open
